### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by juliusregalado** [juliusregalado/Chef-s-Diary-Project-02#1]
I cant seem to find the origin of this error (pasted at the bottom)
What im trying to do:
    - when i submit to create its not moving on to where i want to redirect. but the data is making it all 
      the way to the database and also displays just fine when i got to my display all page.

What ive tried to do:
   - traced it back to the DB file.. but i figured it should'nt be the problem since it is saving it to the DB
   - also tried to fix it on my controllers but just would not work.
==========================================================
TypeError: Cannot read property 'then' of undefined
    at create (/Users/juliusregalado/code/wdi/PROJECTS/Chef-s-Diary-Project-02/controllers/recipeC.js:29:4)
    at Layer.handle [as handle_request] (/Users/juliusregalado/code/wdi/PROJECTS/Chef-s-Diary-Project-02/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/juliusregalado/code/wdi/PROJECTS/Chef-s-Diary-Project-02/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/juliusregalado/code/wdi/PROJECTS/Chef-s-Diary-Project-02/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/juliusregalado/code/wdi/PROJECTS/Chef-s-Diary-Project-02/node_modules/express/lib/router/layer.js:95:5)
    at /Users/juliusregalado/code/wdi/PROJECTS/Chef-s-Diary-Project-02/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/juliusregalado/code/wdi/PROJECTS/Chef-s-Diary-Project-02/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/juliusregalado/code/wdi/PROJECTS/Chef-s-Diary-Project-02/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/juliusregalado/code/wdi/PROJECTS/Chef-s-Diary-Project-02/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/juliusregalado/code/wdi/PROJECTS/Chef-s-Diary-Project-02/node_modules/express/lib/router/index.js:47:12)

**Comment by jsm13** [comment]
Could you push your most recent code? Right now the model file doesn't have a create method

**Comment by juliusregalado** [comment]
just did it before lunch. just came back
